Repository wecode-bootcamp-korea/25-1st-HandWash-frontend, pull requests merged in 2021-10, with the labels that each got.

#4 [25기 전태양] product_layout 구현 완료
  .vscode/settings.json
  public/images/Product/heart.png
  public/images/Product/hmgoepprod (1).jpeg
  public/images/Product/hmgoepprod (2).jpeg
  public/images/Product/hmgoepprod (3).jpeg
  public/images/Product/hmgoepprod (4).jpeg
  public/images/Product/hmgoepprod (5).jpeg
  public/images/Product/hmgoepprod (6).jpeg
  public/images/Product/hmgoepprod.jpeg
  public/images/Product/스크린샷 2021-10-07 오전 1.37.16.png
  pull_request_template.md
  src/Routes.js
  src/index.js
  src/pages/Product/Content/Content.js
  src/pages/Product/ContentInfo/ContentInfo.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/Recommendations/Recommendations.js
  src/pages/Product/Side/Side.js
  src/pages/Product/StyleIntroduce/StyleIntroduce.js
  src/pages/Product/StyleRecommend/StyleRecommend.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#6 [25기 서동혁] login, signup 데이터 통신 정보 수정
  public/data/signUpData.json
  src/Routes.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginInput.js
  src/pages/Product/Side/Side.js
  src/pages/Signup/Component/AddInformation.js
  src/pages/Signup/Component/AddInformation.scss
  src/pages/Signup/Component/Agreementbox.js
  src/pages/Signup/Component/BirthInput.js
  src/pages/Signup/Component/SignupInput.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: 추가 기능 구현중

#16 [25기 조윤희] config.js 추가 및 페이지네이션, 필터링 기능 구현 완료
  src/Routes.js
  src/components/Item/Item.js
  src/components/Item/Item.scss
  src/components/Login/Login.js
  src/config.js
  src/pages/ItemList/FilterNav/FilterNav.js
  src/pages/ItemList/FilterNav/FilterNav.scss
  src/pages/ItemList/FilterNav/FilterRightBar/FilterSideBar.js
  src/pages/ItemList/Itemlist.js
  src/pages/ItemList/Itemlist.scss
  src/pages/ItemList/Items/Items.js
  src/pages/ItemList/Mock/filterlist.js
  src/pages/LoginModal/LoginInput.js
  src/pages/LoginModal/LoginModal.js
  src/pages/LoginModal/LoginModal.scss
  src/pages/Product/Product.js
Labels: Status: 리뷰 요청

#17 [25기 신혜리] nav_function 기능 구현중
  public/data/campaignData.json
  public/data/magazineData.json
  public/data/trendData.json
  public/images/main/campaign_img1.jpg
  public/images/main/campaign_img2.jpg
  public/images/main/magazine_img1.jpg
  public/images/main/magazine_img2.jpg
  public/images/main/magazine_img3.jpg
  public/images/main/trendImg1.jpg
  public/images/main/trendImg10.jpg
  public/images/main/trendImg2.jpg
  public/images/main/trendImg3.jpg
  public/images/main/trendImg4.jpg
  public/images/main/trendImg5.jpg
  public/images/main/trendImg6.jpg
  public/images/main/trendImg7.jpg
  public/images/main/trendImg8.jpg
  public/images/main/trendImg9.jpg
  public/images/main_font.png
  public/images/main_img.jpeg
  src/components/Nav/Depth/Category.js
  src/components/Nav/Depth/Depth.js
  src/components/Nav/Depth/Depth.scss
  src/components/Nav/Depth/SubCategory.js
  src/components/Nav/Login/Login.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/Favorites/FavoritesList/FavoritesModal/FavoritesModal.js
  src/pages/ItemList/Itemlist.js
  src/pages/LoginModal/LoginModal.scss
  src/pages/Main/Campaign/Campaign.js
  src/pages/Main/Magazine/Magazine.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Trend.js
  src/pages/Signup/Signup.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#21 [25기 서동혁] 장바구니 구현
  src/Routes.js
  src/pages/Basket/Basket.js
  src/pages/Basket/Basket.scss
  src/pages/Basket/Basketitem.js
  src/pages/Basket/Payment/ Payment.js
  src/pages/Basket/Payment/Payment.scss
  src/pages/LoginModal/LoginModal.js
  src/pages/Signup/Signup.js
Labels: Status: 리뷰 요청

#19 [25기 전태양] favorites_detail 추가구현
  src/pages/Favorites/Favorites.js
  src/pages/Favorites/FavoritesList/FavoritesList.js
  src/pages/Favorites/FavoritesList/FavoritesModal/FavoritesModal.js
  src/pages/Product/Product.js
  src/pages/Product/Side/SizeModal/SizeModal.js
Labels: Status: 추가 기능 구현중
